<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DocumentOcr</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Idrak" Version="0.2.1" />
    <ProjectReference Include="..\..\src\CnnSamples.Shared\CnnSamples.Shared.csproj" />
  </ItemGroup>

</Project>
